# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DocsSsot < Formula
  desc "Documentation Single Source of Truth (SSOT) generator"
  homepage "https://github.com/hiromaily/docs-ssot"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hiromaily/docs-ssot/releases/download/v0.12.0/docs-ssot_0.12.0_darwin_amd64.tar.gz"
      sha256 "6f6a86ef32e82f305b5fdabccacc779ac709c36f4d5f0b4a17d0dc315e2c9622"

      define_method(:install) do
        bin.install "docs-ssot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hiromaily/docs-ssot/releases/download/v0.12.0/docs-ssot_0.12.0_darwin_arm64.tar.gz"
      sha256 "dfdd2e8dd3a68400c9757e7ed7617772a096a1974f6ff4f50b2e07368e5fc3c1"

      define_method(:install) do
        bin.install "docs-ssot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hiromaily/docs-ssot/releases/download/v0.12.0/docs-ssot_0.12.0_linux_amd64.tar.gz"
      sha256 "6b1a1563cde7841f8593498378bd452824e6550327ef8891a44c4a6c734761bd"
      define_method(:install) do
        bin.install "docs-ssot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hiromaily/docs-ssot/releases/download/v0.12.0/docs-ssot_0.12.0_linux_arm64.tar.gz"
      sha256 "304bbe0abea5c9e22934a6a84a29d23759c4261f1c60f3029b829923ee70903a"
      define_method(:install) do
        bin.install "docs-ssot"
      end
    end
  end

  test do
    system "#{bin}/docs-ssot", "version"
  end
end
