# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoBookTeacher < Formula
  desc "find teacher's lesson"
  homepage "https://github.com/hiromaily/go-book-teacher"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hiromaily/go-book-teacher/releases/download/v1.0.0/go-book-teacher_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "586e7383aff7c432e3fca3c78a8abd276cabe30ca0a322a8b767d110f6edaa6b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/hiromaily/go-book-teacher/releases/download/v1.0.0/go-book-teacher_1.0.0_Linux_x86_64.tar.gz"
    sha256 "798e776ce8fd75c0d894b06dd3297551482ba0a6a827f5b511fe87e1f60fcea1"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/hiromaily/go-book-teacher/releases/download/v1.0.0/go-book-teacher_1.0.0_Linux_arm64.tar.gz"
    sha256 "fd2622c273a83713cde048f640d4686b1a27cc5cafc20caa5fff99e5cbe2a9bb"
  end

  def install
    bin.install Dir['*']
  end

  test do
    system "#{bin}/book-teacher -v"
  end
end
