# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGoogleHome < Formula
  desc "speak message on Google Home"
  homepage "https://github.com/hiromaily/go-google-home"
  version "2.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hiromaily/go-google-home/releases/download/v2.0.0/go-google-home_2.0.0_Darwin_x86_64.tar.gz"
    sha256 "d1e0b321e98f019facf3c82ed1619fbbc80d771f6da03d6fd658c7ab65353c2d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/hiromaily/go-google-home/releases/download/v2.0.0/go-google-home_2.0.0_Linux_x86_64.tar.gz"
    sha256 "9c667f38f0a34cdd45ed1d5324679b644d5a4a42f262d649cf69f4a87cbc5284"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/hiromaily/go-google-home/releases/download/v2.0.0/go-google-home_2.0.0_Linux_arm64.tar.gz"
    sha256 "43affb97efa43deb892daa6ea5f104d21eebe246a529b1d3f0a1f7a622ef76bd"
  end

  def install
    bin.install "gh"
    (etc/"google-home").install "gh.toml"
  end

  def caveats; <<~EOS
    gh has been installed, have fun!
    config file has been installed in /usr/local/etc/google-home/gh.toml
    please modify these files as you want.
    More information:
      https://github.com/hiromaily/go-google-home
  EOS
  end

  test do
    system "#{bin}/gh -v"
  end
end
