# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGoogleHome < Formula
  desc "speak message on Google Home"
  homepage "https://github.com/hiromaily/go-google-home"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hiromaily/go-google-home/releases/download/v1.0.0/go-google-home_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "a7e1041af2d9d852fe32661b89a6c6ff8f712a8435d8f9121a2c541f1e9a6f71"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/hiromaily/go-google-home/releases/download/v1.0.0/go-google-home_1.0.0_Linux_x86_64.tar.gz"
    sha256 "b39887a76d22ea9267b317778b7c8f523ba25308e6c481e9b6f0d3bce02993b3"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/hiromaily/go-google-home/releases/download/v1.0.0/go-google-home_1.0.0_Linux_arm64.tar.gz"
    sha256 "a955eb77a533945efcbc82dc04b9feca233812287be3b98d9afde45d42c51779"
  end

  def install
    bin.install "gh"
    (etc/"google-home").install "gh.toml"
  end

  def caveats; <<~EOS
    gh has been installed, have fun!
    config file has been installed in /usr/local/etc/google-home/gh.toml
    please modify these files as you want.
    More information:
      https://github.com/hiromaily/go-google-home
  EOS
  end

  test do
    system "#{bin}/gh -v"
  end
end
