# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGoogleHome < Formula
  desc "speak message on Google Home"
  homepage "https://github.com/hiromaily/go-google-home"
  version "2.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hiromaily/go-google-home/releases/download/v2.0.0/go-google-home_2.0.0_Darwin_x86_64.tar.gz"
    sha256 "5f537e6bf8693486b8a9376d78b965a51699412818d6047413303485461bdf60"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/hiromaily/go-google-home/releases/download/v2.0.0/go-google-home_2.0.0_Linux_x86_64.tar.gz"
    sha256 "786b57f1175e00f3550e3fb70fa84acdc31b0ef29ec4a9719014285346514187"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/hiromaily/go-google-home/releases/download/v2.0.0/go-google-home_2.0.0_Linux_arm64.tar.gz"
    sha256 "22484add0b626a49e79b6406e1d9c90896811929458a1a4babc10d220891a9f2"
  end

  def install
    bin.install "gh"
    (etc/"google-home").install "gh.toml"
  end

  def caveats; <<~EOS
    gh has been installed, have fun!
    config file has been installed in /usr/local/etc/google-home/gh.toml
    please modify these files as you want.
    More information:
      https://github.com/hiromaily/go-google-home
  EOS
  end

  test do
    system "#{bin}/gh -v"
  end
end
